module.exports = [
  `bracketend`,
  `bracketstart`,
  `colon`,
  `comma`,
  `curlystart`,
  `curlyend`,
  `equals`,
  `identifier`,
  `numberliteral`,
  `space`,
  `statementend`,
  `stringliteral`,
  `stringend`,
  `stringstart`,
];