console.log(`[Testing...]`);
console.log(`[browser Template: pipe]`);
require(`./pipe-test`);
console.log(`[browser Template: if]`);
require(`./if-test`);
console.log(`[browser Template: while]`);
require(`./while-test`);
console.log(`[browser Template: for]`);
require(`./for-test`);
console.log(`[browser Template: map]`);
require(`./map-test`);
console.log(`[browser Template: fn]`);
require(`./fn-test`);
console.log(`[browser Template: state]`);
require(`./state-test`);
console.log(`[lex]`);
require(`./lex-test.js`);
console.log(`[generate]`);
require(`./generate-js-test`);